version: '3'
services:
  ## 网盘
  ## docker run -d --name aria2-ui -p 80:80 -p 6800:6800 wahyd4/aria2-ui
  ## 访问地址：http://ip:18005/ http://ip:18005/files
  ## 登陆密码 admin admin

  pan:
    container_name: pan
    image: wahyd4/aria2-ui
    ports:
    - 80:80
    - 6800:6800
    volumes:
    - /root/compose/pan:/data
    privileged: true


  ## nginx
  ## docker create --name nginx_1 -p 10022:22 -p 15000:80 --privileged=true -ti nginx
 
  nginx:
    container_name: nginx
    image: docker.io/nginx
    ports:
    - 15000:80
    volumes:
    - $PWD/nginx/www:/www
    - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    - $PWD/nginx/logs:/wwwlogs
    privileged: true

  ubuntu_test:
   build:
     context: ./localApp1
     dockerfile: Dockerfile
   image: ubuntu_test
  
  mysql_parse:
   build:
     context: ./mysqlParse
     dockerfile: Dockerfile
   image: mysql_parse:v1
   ports:
    - 18000:80
