## docker-compose 运行
## docker-compose -f xxx.yml start
## docker-compose -f xxx.yml build base_image_by_ubuntu
## docker-compose -f docker-compose-pro.yml build base_image_by_ubuntu

##
## docker-compose -f docker-compose-pro.yml start  worm_v1


##docker-compose -f docker-compose-pro.yml up -d

version: '3'
services:
  ## nginx
  ## docker create --name nginx -p 10022:22 -p 15000:80 --privileged=true -ti nginx
  ## 基础镜像
  base_image_by_ubuntu:
    build:
      context: ./baseImage
      dockerfile: Dockerfile
    image: chao313/base_image_by_ubuntu:v1.0

    ## 基础镜像
  worm:
    build:
      context: ./worm
      dockerfile: Dockerfile
    image: chao313/worm:v1.0

  base_image_by_php_mysql_5_6:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: chao313/base_image_by_php_mysql_5_6:v1.0