## docker-compose 运行
## docker-compose -f create_mysql_users.sh.yml start
## docker-compose -f create_mysql_users.sh.yml build base_image_by_ubuntu
## docker-compose -f docker-compose-pro.yml build base_image_by_ubuntu

##
## docker-compose -f docker-compose-pro.yml start  worm_v1


##docker-compose -f docker-compose-pro.yml up -d

version: '3'
services:
  ## nginx
  ## docker create --name nginx -p 10022:22 -p 15000:80 --privileged=true -ti nginx
  nginx:
    container_name: nginx
    image: docker.io/nginx
    ports:
    - 80:80
    volumes:
    - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  ## wormV1
  worm_v1:
    container_name: worm_v1
    image: chao313/worm:v1.0
    ports:
    - 18888:80
    privileged: true


  ## 基础镜像
  base_image_by_ubuntu:
    build:
      context: ./baseImage
      dockerfile: Dockerfile
    image: chao313/base_image_by_ubuntu:v1.0

    ## 基础镜像
  worm:
    build:
      context: ./worm
      dockerfile: Dockerfile
    image: chao313/worm:v1.0